#!/usr/bin/python

import sys
import time
import csv
import epics
from epics import caget, caput
import keith_func
import global_uut_settings

uut = global_uut_settings.uut
ai_site = global_uut_settings.ai_site
ao_site = global_uut_settings.ao_site

print sys.argv[0]
print sys.argv[1]

complete = 0


############ Begin setting AO voltages and reading back from Keithley #########
set_AO_all(5,4)
Vall = keith_func.pull_ch_all(32)
print Vall

set_AO_all(3,4)
Vall = keith_func.pull_ch_all(32)
print Vall

############ Set output filename and open for CSV writing #########
result_file = open('./results/results.csv','wb')
csv_write = csv.writer(result_file)
#Create header for CSV
channel_header  = ['CH{0:0>2}'.format(i) for i in range(1, 32+1)]
channel_header.insert(0,'Req. Voltage') # Insert another heading
csv_write.writerow(channel_header)

############ Loop everything for an AO set and readback ############
#nchan = 4
#
#for voltage in range (0, 6):
#    print voltage
#    set_AO_all(voltage,nchan)
#    Vall = keith_func.pull_ch_all(nchan)
#    csv_write.writerow(Vall)
#    print Vall
#
#dac_code_array = keith_func.getDacCodes_all(32)
#print dac_code_array

############ Individual voltage per CH stored in list of lists ############
nchan = 4
results_array = []      # Initialise array to store results
voltages = range(0,6)   # Specify voltages to loop through

for i in range (0, len(voltages)):
    results_array.append([])   # Add another sublist to master list
    results_array[i].append(voltages[i])  # Add requested voltage to sublist
    for channel in range (1,nchan+1):
        set_AO(voltages[i],channel)   # Set AO on current channel
        v = keith_func.getKVolts(channel,nchan) # Get recorded voltage from KMUX
        results_array[i].append(v) # Append recorded voltage to sublist
        #print v       
        set_AO_all(0,nchan)
    csv_write.writerow(results_array[i])  # Write to CSV, format as below


# Format of CSV generated by above
# Req V,  CH01,  CH02,  CH03,  CH04
#  0   , 0.047, -0.02,  0.03, 0.037
#  1   , 1.047, -0.02,  0.02, 0.030
